# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
# then modified manually
{ lib, buildGoModule, fetchgit
, bash, coreutils, procps, iproute
}:

buildGoModule rec {
  pname = "batexpe";
  version = "1.2.0+";

  # goPackagePath = "framagit.org/batsim/batexpe";

  src = fetchgit {
    rev = "d4298236";
    url = "https://framagit.org/batsim/batexpe.git";
    sha256 = "sha256-vYxOCHMwX20Xf3mVy9AjGzaQ4GghSWV1QB2II8kvPAQ=";
  };

  propagatedBuildInputs = [bash coreutils procps iproute];

  # goDeps = ./deps.nix;
  vendorHash = "sha256-LNu+L1PN6sY1fNqXhoQ404h4BvTJfmZAa8tVWt/HRoM=";

  meta = with lib; {
    description = "set of Go tools around Batsim to simplify experiments";
    longDescription = ''
      It includes:
      - robin: manages the execution of one simulation. It is meant to be as
        robust as possible, as it is the core building block to create experiment
        workflows with Batsim.
      - robintest: is a robin wrapper mainly used to test robin.  robintest
        notably allows to specify what (robin/batsim/scheduler) result is
        expected.
      - the multiple commands are just wrappers around the batexpe library
        (written in Go).  This allows users to build their own tools (in Go) with
        decent code reuse.
    '';
    license = licenses.lgpl3;
    broken = false;
    maintainers = with maintainers; [ mickours ];
    platforms = iproute.meta.platforms;
  };
}